version: '3'

services:
  db:
    image: postgres
    environment:
      POSTGRES_DB: merightnow
      POSTGRES_USER: vaelev
      POSTGRES_PASSWORD: innsbruck
    volumes:
      - postgres_data:/var/lib/postgresql/data

  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - "8001:8000"
    depends_on:
      - db
    environment:
      - DATABASE_HOST=db

volumes:
  postgres_data:
